# Generated by Django 3.2.6 on 2021-08-24 14:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Image_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('caption', models.CharField(max_length=256)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('type', models.CharField(choices=[('I', 'Images'), ('V', 'Video')], max_length=1)),
            ],
        ),
    ]
