# Generated by Django 3.2.6 on 2021-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image_video',
            name='type',
            field=models.CharField(choices=[('I', 'Image'), ('V', 'Video')], default='Image', max_length=1),
        ),
    ]
