# Generated by Django 3.2.6 on 2021-08-22 14:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=32)),
                ('video', models.FileField(blank=True, null=True, upload_to=api.models.upload_video_path)),
            ],
        ),
    ]
